### ISSUE TITLE
mstpr-brainbot - Redeeming stake tokens is not updating the pool's borrowing fee rate

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-elfi-protocol-judging#137]
mstpr-brainbot

High

# Redeeming stake tokens is not updating the pool's borrowing fee rate

## Summary
Just like minting new stake tokens, redeeming minting stake tokens also changes the pools base amount without updating the pools borrowing fee rate. 
## Vulnerability Detail
When stake tokens are redeemed, the base amount changes:
```solidity
function _executeRedeemStakeToken(
        LpPool.Props storage pool,
        Redeem.Request memory params,
        address baseToken
    ) internal returns (uint256) {
        //.
        -> pool.subPoolAmount(pool.baseToken, cache.redeemTokenAmount);
        .
    }
```

However, this change does not update the overall borrowing fee rate.
## Impact
Unfair accrual of borrowing fees. It can yield on lesser/higher fees for lps and position holders. It can also delay or cause unfair liquidations. Hence, high.
## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/process/RedeemProcess.sol#L133-L183

https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/process/MarketQueryProcess.sol#L82C5-L108
## Tool used

Manual Review

## Recommendation

Duplicate of #136

**Comment by mstpr** [comment]
Escalate

This shouldn't be a dup of #136. The fix of #136 will not fix this issue. Although the fixes are very similar these issues are completely separate. Both issues are missing additional code rather than a removal of code or a logic mistake.

From Sherlock docs on dup issues:
"The exception to this would be if underlying code implementations, impact, and the fixes are different, then they can be treated separately." 

I think this should be classified as a separate high priority issue.

**Comment by sherlock-admin4** [comment]
> Escalate
> 
> This shouldn't be a dup of #136. The fix of #136 will not fix this issue. Although the fixes are very similar these issues are completely separate. Both issues are missing additional code rather than a removal of code or a logic mistake.
> 
> From Sherlock docs on dup issues:
> "The exception to this would be if underlying code implementations, impact, and the fixes are different, then they can be treated separately." 
> 
> I think this should be classified as a separate high priority issue.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
I believe these issues are duplicates as the root cause is the same as they issues with the same logic/conceptual mistake per highlighted [here](https://docs.sherlock.xyz/audits/judging/judging#ix.-duplication-rules)(see the section under Root cause groupings)

**Comment by WangSecurity** [comment]
I agree with the lead judge that these two reports have the same root cause: the mistake of not updating the borrowing fee rate. The impacts are the same. Even though these 2 reports require separate fixes, I believe these should remain duplicates.

Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
High
Duplicate of #136

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [mstpr](https://github.com/sherlock-audit/2024-05-elfi-protocol-judging/issues/137/#issuecomment-2210819332): rejected

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
