### ISSUE TITLE
ZeroTrust - The profits of LpPool  are not included in AvailableLiquidity in `getPoolAvailableLiquidity()`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-elfi-protocol-judging#240]
ZeroTrust

Medium

# The profits of LpPool  are not included in AvailableLiquidity in `getPoolAvailableLiquidity()`

## Summary
The profits of LpPool  are not included in AvailableLiquidity in `getPoolAvailableLiquidity()`
## Vulnerability Detail
```javascript
 function getPoolAvailableLiquidity(
        LpPool.Props storage pool,
        OracleProcess.OracleParam[] memory oracles
    ) public view returns (uint256) {
        int256 baseTokenAmount = pool.baseTokenBalance.amount.toInt256() + pool.baseTokenBalance.unsettledAmount;
        if (baseTokenAmount < 0) {
            return 0;
        }

        address[] memory stableTokens = pool.getStableTokens();
        if (stableTokens.length > 0) {
            uint8 baseTokenDecimals = TokenUtils.decimals(pool.baseToken);
            int256 baseTokenPrice = OracleProcess.getIntOraclePrices(oracles, pool.baseToken, true);
            for (uint256 i; i < stableTokens.length; i++) {
                LpPool.TokenBalance storage tokenBalance = pool.stableTokenBalances[stableTokens[i]];
                if (
@>>                    tokenBalance.lossAmount > 0 &&
@>>                    tokenBalance.amount.toInt256() + tokenBalance.unsettledAmount < tokenBalance.lossAmount.toInt256()
                ) {
                    int256 tokenUsd = CalUtils.tokenToUsdInt(
                        tokenBalance.lossAmount.toInt256() -
                            tokenBalance.amount.toInt256() -
                            tokenBalance.unsettledAmount,
                        TokenUtils.decimals(stableTokens[i]),
                        OracleProcess.getIntOraclePrices(oracles, stableTokens[i], true)
                    );
                    int256 stableToBaseToken = CalUtils.usdToTokenInt(tokenUsd, baseTokenDecimals, baseTokenPrice);
                    if (baseTokenAmount > stableToBaseToken) {
                        baseTokenAmount -= stableToBaseToken;
                    } else {
                        baseTokenAmount = 0;
                    }
                }
            }
        }
        int256 availableTokenAmount = CalUtils.mulRate(baseTokenAmount, pool.getPoolLiquidityLimit().toInt256());
        return
            availableTokenAmount > pool.baseTokenBalance.holdAmount.toInt256()
                ? (availableTokenAmount - pool.baseTokenBalance.holdAmount.toInt256()).toUint256()
                : 0;
    }
```
We can see that only when the pool has losses, and the losses are greater than the profits, the difference in the loss of stablecoins (i.e., the user’s profit) is calculated. However, stablecoin profits are not accounted for in cases where there are profits.

## Impact
The expected liquidity is not correctly calculated, affecting the liquidity providers’ ability to withdraw their tokens.
## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/LpPoolQueryProcess.sol#L151
## Tool used

Manual Review

## Recommendation
```diff
if (
-                   tokenBalance.lossAmount > 0 &&
-                   tokenBalance.amount.toInt256() + tokenBalance.unsettledAmount < tokenBalance.lossAmount.toInt256()
+                    tokenBalance.lossAmount > 0 || tokenBalance.amount > 0 || tokenBalance.unsettledAmount > 0
                )
```

**Comment by ZeroTrust01** [comment]
> When the baseToken pool contains stablecoins, it is in a profitable state, but these have not been converted into baseTokens. Therefore, they cannot serve as available liquidity for baseTokens. Conversely, in a loss situation, this portion needs to be excluded to ensure the pool has sufficient funds to repay the USD Pool


First, let me clarify the basic consensus on this issue:

The baseToken pool definitely includes stablecoins, such as in the WETH-USDC pair, which naturally includes the stablecoin USDC. The following structure records the profit and loss for  the baseToken pool. The unsettledAmount is in a profitable state for the baseToken pool(short users loss), but these have not been converted into baseTokens.

```javascript
struct TokenBalance {
        uint256 amount;
        uint256 liability;
        uint256 holdAmount;
@>        int256 unsettledAmount;
@>        uint256 lossAmount;
        EnumerableMap.AddressToUintMap collateralTokenAmounts;
    }

mapping(address => TokenBalance) stableTokenBalances;

```
The sponsor mentioned: “The unsettledAmount is in a profitable state, but these have not been converted into baseTokens. Therefore, they cannot serve as available liquidity for baseTokens.” 

**I believe this is unreasonable because the baseTokens.unsettledAmount is also in a profitable state.**

_Why can baseTokens.unsettledAmount serve as available liquidity?_

Or is it that stablecoins.unsettledAmount cannot be converted into baseTokens?

@nevillehuang @0xELFi

**Comment by 0502lian** [comment]
Escalate
This should be a valid issue. It points out that the LpPool’s short position profits are not reflected in liquidity

**Comment by sherlock-admin3** [comment]
> Escalate
> This should be a valid issue. It points out that the LpPool’s short position profits are not reflected in liquidity 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xELFi** [comment]
The baseToken unsettled amount and stable tokens relative to the baseToken amount indeed represent baseTokens that have not actually been received. However, there is a fundamental difference here. The baseToken unsettled amount in our system design is considered a portfolio debt, which can always repay the corresponding token amount. This relies on our risk control system for protection. On the other hand, the amount of stable tokens we record can lead to the pool being unable to cover the trade's profits due to significant fluctuations in the baseToken's price. For the stablecoins in the pool, we convert them into baseToken every 24 hours(RebalanceFacet.sol). Therefore, the profit assets from stablecoins are only delayed by 0-24 hours for validation as available liquidity, which mainly affects opening positions and withdrawals. For other pool-related logic, the gains and losses of stable tokens are calculated in real-time.

**Comment by 0502lian** [comment]
> I believe this is unreasonable because the baseTokens.unsettledAmount is also in a profitable state.


Why does baseTokens.unsettledAmount serve as available liquidity if it is in a profitable state? It could also be counted only when it is realized.

Because getPoolAvailableLiquidity() affects functions like increasing positions and redeeming liquidity for users, the profits that should be counted are delayed by 0-24 hours (according to the sponsor’s confirmed information).

Additionally, since these are shorting profits and the scale is huge, it will intermittently cause DoS issues for users’ functions like increasing positions and redeeming liquidity.

Therefore, I believe this is a valid issue.

**Comment by WangSecurity** [comment]
I believe it's a design decision and the report shows only a more optional way to function. Hence, I believe this report should remain invalid. Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0502lian](https://github.com/sherlock-audit/2024-05-elfi-protocol-judging/issues/240/#issuecomment-2209661350): rejected
